package main

const classnameField = "classname"
const fullMessageField = "full_message"
const levelColorField = "_level_color"
const levelField = "level"
const statusField = "status"
const logLevelField = "loglevel"
const longTimestampField = "_long_time_timestamp"
const messageField = "message"
const messageTextField = "_message_text"
const jsonField = "_json"
const originalMessageField = "original_message"
const requestPageField = "request_page"
const resetField = "_reset"
const shortClassnameField = "_short_classname"
const timestampField = "timestamp"
const logStatusField = "log_status"
